### ISSUE TITLE
Feature Request: contextual menu

### ISSUE THREAD

**Issue by devolution2409** [Gabsii/getter-setter-generator#5]
Could be great to have the extension comes with contextual menu via default, you can right click a member variable to generate the getters and setters instead of pressing ctrl alt D :)

on a side note: it would be nice if the plugin could differentiate between headers and source file, so that it would add the getters/setters prototypes in headers, and implementation in source

**Comment by Gabsii** [comment]
Hello @devolution2409 !

First of all, thank you for your submission. I am always happy seeing issues being posted and features being discussed! 😄
Do you have any references or ideas for the context menu? Maybe mockups would help.
Differentiating between header and source files is currently in development, sorry for the delays!

Thanks again for your input!
Gabsii

**Comment by devolution2409** [comment]
Woops wrong topic :)

I meant a menu that add "generate getter/setters" when you right click on a variable. It would then add the getter/setters in the .h file :)
