### ISSUE TITLE
[Feature Request] separate commands for generating getters and setters

### ISSUE THREAD

**Issue by theFlyingCat04** [Gabsii/getter-setter-generator#6]
It would be nice to have two separate commands to generate the getters and setters:
In some situations I only wan't to have getters, in other situations I just want the setters. As a very simple (and pretty stupid) example you have a class, that adds two members: 
```
class AddingNumbers {
public:

	void setFirstNum(int num) {
		num1 = num;
	}
	void setSecondNum(int num) {
		num2 = num;
	}

	void add() {
		result = num1 + num2;
	}

	int getResult {
		return result;
	}

private:
	int num1;
	int num2;
	int result;
};
```
For the two numbers to add just the setters are needed, for the result You only need a getter.

Yes, I could generate both (getters and setters) and delete the unnecessary parts, but it would be a little more time saving if there were two additional commands.

**Comment by Gabsii** [comment]
Hello @theFlyingCat04! 

First of all, thank you for your submission. I am always happy seeing issues being posted and features being discussed! 😄 
I am currently working on decoupling the getter/setter generation process. With the next release, you should be able to generate getter and setter separately via the command palette! 

Thanks again for your input!
Gabsii

**Comment by theFlyingCat04** [comment]
That sounds great! Thank You.
